import {useEffect,useRef,useState} from 'react';
import * as maplibregl from 'maplibre-gl';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
maplibregl.setWorkerUrl(workerUrl);
import {Aircraft} from './api';
export default function MapView({aircraft,selected,onSelect,heatmap,trajectory,hotspots}:{aircraft:Aircraft[];selected:Aircraft|null;onSelect:(a:Aircraft)=>void;heatmap:boolean;trajectory:any;hotspots:any}){
 const element=useRef<HTMLDivElement>(null),map=useRef<maplibregl.Map|null>(null);const [ready,setReady]=useState(false),[error,setError]=useState('');const data=useRef(aircraft);const callback=useRef(onSelect);data.current=aircraft;callback.current=onSelect;
 useEffect(()=>{if(!element.current)return;let m:maplibregl.Map;try{m=new maplibregl.Map({container:element.current,center:[9,48],zoom:3.6,style:{version:8,sources:{base:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'&copy; OpenStreetMap contributors'}},layers:[{id:'base',type:'raster',source:'base',paint:{'raster-saturation':-0.8,'raster-brightness-max':0.45,'raster-contrast':0.25}}]}});map.current=m;m.on('error',()=>setError('Map tiles unavailable. Check your internet connection.'));m.addControl(new maplibregl.NavigationControl(),'bottom-right');m.on('load',()=>{m.addSource('aircraft',{type:'geojson',data:{type:'FeatureCollection',features:[]}});m.addLayer({id:'density',type:'heatmap',source:'aircraft',paint:{'heatmap-radius':32,'heatmap-opacity':0.6}});m.addLayer({id:'aircraft',type:'circle',source:'aircraft',paint:{'circle-radius':['interpolate',['linear'],['zoom'],2,3,8,7],'circle-color':'#c5e882','circle-stroke-color':'#151c17','circle-stroke-width':2}});m.addSource('hotspots',{type:'geojson',data:{type:'FeatureCollection',features:[]}});m.addLayer({id:'hotspots',type:'circle',source:'hotspots',paint:{'circle-radius':['interpolate',['linear'],['get','count'],1,12,10,28,50,55,200,85],'circle-color':'#ef935c','circle-opacity':0.2,'circle-stroke-color':'#ef935c','circle-stroke-width':2}});m.on('click','hotspots',e=>{const f=e.features?.[0];if(f)new maplibregl.Popup().setLngLat(e.lngLat).setText(`${f.properties?.count} active alerts / ${f.properties?.aircraft_count} aircraft in this area`).addTo(m)});m.addSource('trajectory',{type:'geojson',data:{type:'FeatureCollection',features:[]}});m.addLayer({id:'trajectory',type:'line',source:'trajectory',paint:{'line-color':'#c5e882','line-width':4}});m.on('click','aircraft',e=>{const id=e.features?.[0]?.properties?.icao24;const a=data.current.find(x=>x.properties.icao24===id);if(a)callback.current(a)});m.on('mouseenter','aircraft',()=>{m.getCanvas().style.cursor='pointer'});m.on('mouseleave','aircraft',()=>{m.getCanvas().style.cursor=''});setReady(true)});}catch{setError('The map could not start. Check WebGL support in your browser.')}return()=>{m?.remove();map.current=null;setReady(false)}},[]);
 useEffect(()=>{if(!ready||!map.current)return;(map.current.getSource('aircraft') as maplibregl.GeoJSONSource).setData({type:'FeatureCollection',features:aircraft} as any);map.current.setLayoutProperty('density','visibility',heatmap?'visible':'none')},[ready,aircraft,heatmap]);
 useEffect(()=>{if(ready&&selected)map.current?.flyTo({center:selected.geometry.coordinates.slice(0,2) as [number,number],zoom:6,duration:1200})},[ready,selected]);
 useEffect(()=>{if(!ready||!map.current)return;(map.current.getSource('trajectory') as maplibregl.GeoJSONSource).setData(trajectory?.geometry?trajectory:{type:'FeatureCollection',features:[]});const coords=trajectory?.geometry?.coordinates;if(coords?.length>=2){const bounds=new maplibregl.LngLatBounds();coords.forEach((c:number[])=>bounds.extend([c[0],c[1]]));map.current.fitBounds(bounds,{padding:{top:60,bottom:70,left:Math.min(330,map.current.getContainer().clientWidth/3),right:40},maxZoom:9,duration:900})}},[ready,trajectory]);
 useEffect(()=>{if(ready)(map.current?.getSource('hotspots') as maplibregl.GeoJSONSource)?.setData(hotspots||{type:'FeatureCollection',features:[]})},[ready,hotspots]);
 return <><div className="map" ref={element}/>{error&&<div className="map-error">{error}</div>}</>;
}

