import {FormEvent,lazy,Suspense,useEffect,useRef,useState} from 'react';
import {api,Aircraft,errorMessage} from './api';
const MapView=lazy(()=>import('./MapView'));
const empty={type:'FeatureCollection',features:[]};
const fmt=(n:number|null|undefined)=>n==null?'Unavailable':Math.round(n).toLocaleString();
function circle(lon:number,lat:number,radius:number){const coordinates:number[][]=[];const rad=Math.PI/180,d=radius/6371,phi=lat*rad,lambda=lon*rad;for(let i=0;i<=96;i++){const bearing=i/96*2*Math.PI;const p=Math.asin(Math.sin(phi)*Math.cos(d)+Math.cos(phi)*Math.sin(d)*Math.cos(bearing));const l=lambda+Math.atan2(Math.sin(bearing)*Math.sin(d)*Math.cos(phi),Math.cos(d)-Math.sin(phi)*Math.sin(p));coordinates.push([l/rad,p/rad])}return {type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Polygon',coordinates:[coordinates]},properties:{name:`${radius} km search radius`}}]}}
function Results({aircraft,onTrack}:{aircraft:Aircraft[];onTrack:(a:Aircraft)=>void}){return <section className="table-panel"><div className="panel-heading">SEARCH RESULTS <span className="tag">{aircraft.length} aircraft</span></div><div className="table-scroll"><table><thead><tr><th>CALLSIGN / ICAO24</th><th>COUNTRY</th><th>DISTANCE</th><th>ALTITUDE</th><th>SPEED</th><th>LAST OBSERVED</th><th/></tr></thead><tbody>{aircraft.map(a=><tr key={a.properties.icao24}><td><strong>{a.properties.callsign||'Unknown callsign'}</strong><small className="icao-label">{a.properties.icao24.toUpperCase()}</small></td><td>{a.properties.origin_country||'Unavailable'}</td><td>{(a.properties as any).distance_km==null?'—':`${(a.properties as any).distance_km} km`}</td><td>{fmt(a.properties.altitude)} m</td><td>{fmt(a.properties.velocity==null?null:a.properties.velocity*3.6)} km/h</td><td>{new Date(a.properties.last_update).toLocaleString()}</td><td><button className="secondary" onClick={()=>onTrack(a)}>View flight</button></td></tr>)}</tbody></table></div>{!aircraft.length&&<div className="empty">No recent aircraft match this search. Data must have been observed within 30 minutes.</div>}</section>}
function ToolMap({aircraft=[],overlay,onBounds,onTrack}:{aircraft?:Aircraft[];overlay?:any;onBounds?:(b:number[])=>void;onTrack:(a:Aircraft)=>void}){return <section className="map-panel"><div className="panel-heading">AREA MAP <span className="muted">Tap an aircraft to view its flight</span></div><div className="map-wrap"><Suspense fallback={<div className="empty">Loading map...</div>}><MapView aircraft={aircraft} selected={null} onSelect={onTrack} heatmap={false} trajectory={null} hotspots={null} overlay={overlay} onBounds={onBounds}/></Suspense></div></section>}
export function SpatialExplorer({onTrack}:{onTrack:(a:Aircraft)=>void}){
 const [mode,setMode]=useState('radius'),[lat,setLat]=useState('28.614'),[lon,setLon]=useState('77.209'),[radius,setRadius]=useState('50'),[bounds,setBounds]=useState<number[]>([]),[auto,setAuto]=useState(true),[aircraft,setAircraft]=useState<Aircraft[]>([]),[overlay,setOverlay]=useState<any>(empty),[busy,setBusy]=useState(false),[status,setStatus]=useState('Set a center and radius to explore nearby aircraft.'),[limit,setLimit]=useState('1000');const request=useRef(0);
 async function search(b?:number[]){const version=++request.current;setBusy(true);setStatus('Searching...');try{let response;if(mode==='radius'){response=await api.get('/aircraft/near',{params:{lat:Number(lat),lon:Number(lon),radius_km:Number(radius),limit:Number(limit)}});if(version!==request.current)return;setAircraft((response.data.aircraft||[]).map((a:any)=>({type:'Feature',geometry:{type:'Point',coordinates:a.coordinates},properties:a})));setOverlay(circle(Number(lon),Number(lat),Number(radius)))}else{const area=b||bounds;if(area.length!==4)throw Error('Wait for the map to load.');response=await api.get('/aircraft/viewport',{params:{min_lon:area[0],min_lat:area[1],max_lon:area[2],max_lat:area[3],limit:Number(limit)}});if(version!==request.current)return;setAircraft(response.data.features||[]);setOverlay(empty)}setStatus(`${response.data.count} recent aircraft returned.${response.data.count>=Number(limit)?' Result limit reached; narrow the area or increase the limit.':''}`)}catch(e){if(version===request.current){setAircraft([]);setStatus(errorMessage(e))}}finally{if(version===request.current)setBusy(false)}}
 useEffect(()=>{if(mode!=='viewport'||!auto||bounds.length!==4)return;const timer=setTimeout(()=>search(bounds),400);return()=>clearTimeout(timer)},[mode,auto,bounds,limit]);
 useEffect(()=>()=>{request.current++},[]);
 function switchMode(value:string){request.current++;setMode(value);setAircraft([]);setOverlay(empty);setBusy(false);setStatus(value==='radius'?'Set a center and radius to explore nearby aircraft.':'Pan or zoom to search the visible map area.')}
 return <div className="spatial-workspace"><section className="tool-card"><div className="tool-title"><h2>Find aircraft in an area</h2><p>Search the latest stored positions, observed within the last 30 minutes.</p></div><div className="tabs">{['radius','viewport'].map(value=><button key={value} className={mode===value?'selected':''} onClick={()=>switchMode(value)}>{value==='radius'?'Radius search':'Map viewport'}</button>)}</div><form onSubmit={(e:FormEvent)=>{e.preventDefault();search()}}><div className="tool-fields">{mode==='radius'?<><label>Latitude<input type="number" step="any" min="-90" max="90" required value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Longitude<input type="number" step="any" min="-180" max="180" required value={lon} onChange={e=>setLon(e.target.value)}/></label><label>Radius (km)<input type="number" step="any" min="0.1" max="1000" required value={radius} onChange={e=>setRadius(e.target.value)}/></label></>:<label className="check-field"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Search automatically when the map moves</label>}<label>Result limit<select value={limit} onChange={e=>setLimit(e.target.value)}>{[100,1000,5000,10000].map(n=><option key={n}>{n}</option>)}</select></label><button className="primary" disabled={busy}>{busy?'Searching...':mode==='radius'?'Search radius':'Search this map area'}</button></div></form><p className="tool-status" role="status">{status}</p>{mode==='viewport'&&bounds.length===4&&<small className="muted">Bounds: {bounds.map(n=>n.toFixed(3)).join(', ')} (west, south, east, north)</small>}</section><ToolMap aircraft={aircraft} overlay={overlay} onBounds={setBounds} onTrack={onTrack}/><Results aircraft={aircraft} onTrack={onTrack}/></div>
}
export function DensityAnalysis({onTrack}:{onTrack:(a:Aircraft)=>void}){
 const [resolution,setResolution]=useState('5'),[minimum,setMinimum]=useState('5'),[cells,setCells]=useState<any[]>([]),[overlay,setOverlay]=useState<any>(empty),[busy,setBusy]=useState(false),[status,setStatus]=useState('Choose a grid resolution and minimum sample count.');
 async function load(e:FormEvent){e.preventDefault();setBusy(true);setOverlay(empty);setCells([]);try{const {data}=await api.get('/heatmap/density',{params:{resolution:Number(resolution),min_count:Number(minimum)}});const rows=data.cells||[];setCells(rows);setOverlay({type:'FeatureCollection',features:rows.filter((c:any)=>c.boundary?.length).map((c:any)=>({type:'Feature',geometry:{type:'Polygon',coordinates:[[...c.boundary,c.boundary[0]]]},properties:c}))});setStatus(`${rows.length} cells returned${rows.length>=1000?' (maximum 1,000 cells)':''}. Counts represent position samples from the last hour, not unique aircraft.`)}catch(e){setStatus(errorMessage(e))}finally{setBusy(false)}}
 return <div className="spatial-workspace"><section className="tool-card"><div className="tool-title"><h2>Aircraft density by hexagon</h2><p>Compare recorded traffic across geographic cells. Brighter cells contain more observations.</p></div><form onSubmit={load}><div className="tool-fields"><label>Grid resolution<select value={resolution} onChange={e=>setResolution(e.target.value)}>{Array.from({length:16},(_,n)=><option key={n} value={n}>{n}{n===0?' / coarsest':n===15?' / finest':''}</option>)}</select></label><label>Minimum samples<input type="number" min="1" required value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Analyzing...':'Analyze density'}</button></div></form><p role="status" className="tool-status">{status}</p></section><ToolMap overlay={overlay} onTrack={onTrack}/><section className="table-panel"><div className="panel-heading">CELL STATISTICS <span className="tag">Last hour</span></div><div className="table-scroll"><table><thead><tr><th>H3 CELL</th><th>POSITION SAMPLES</th><th>AVG ALTITUDE</th><th>AVG SPEED</th></tr></thead><tbody>{cells.map(c=><tr key={c.h3_cell}><td>{c.h3_cell}</td><td>{c.count}</td><td>{fmt(c.avg_altitude)} m</td><td>{fmt(c.avg_velocity==null?null:c.avg_velocity*3.6)} km/h</td></tr>)}</tbody></table></div>{!cells.length&&<div className="empty">No cells to display. Run an analysis or lower the minimum sample count.</div>}</section></div>
}
export function GeofenceManager({onTrack,canManage}:{onTrack:(a:Aircraft)=>void;canManage:boolean}){
 const [fences,setFences]=useState<any[]>([]),[chosen,setChosen]=useState(''),[aircraft,setAircraft]=useState<Aircraft[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[coordinates,setCoordinates]=useState('77.0, 28.4\n77.4, 28.4\n77.4, 28.8\n77.0, 28.8');const version=useRef(0);
 async function load(){try{const {data}=await api.get('/geofences');setFences(data.features||[])}catch(e){setStatus(errorMessage(e))}}
 useEffect(()=>{load();return()=>{version.current++}},[]);
 async function inspect(id:string){setChosen(id);setAircraft([]);const current=++version.current;setBusy(true);try{const {data}=await api.get(`/geofences/${encodeURIComponent(id)}/aircraft?limit=1000`);if(current!==version.current)return;setAircraft(data.features||[]);setStatus(`${data.count} recent aircraft inside this zone.${data.count>=1000?' Result limit reached (1,000).':''}`)}catch(e){if(current===version.current)setStatus(errorMessage(e))}finally{if(current===version.current)setBusy(false)}}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{const points=coordinates.trim().split(/\n/).map(line=>line.split(',').map(s=>Number(s.trim())));if(points.some(p=>p.length!==2||p.some(n=>!Number.isFinite(n))))throw Error('Use one longitude, latitude pair per line.');const {data}=await api.post('/geofences',{name,coordinates:points});await load();setName('');await inspect(String(data.properties.id))}catch(e){setStatus(e instanceof Error&& !('response' in e)?e.message:errorMessage(e))}finally{setBusy(false)}}
 async function deactivate(){setBusy(true);try{await api.post(`/geofences/${chosen}/deactivate`);version.current++;setChosen('');setAircraft([]);await load();setStatus('Zone deactivated. Existing alerts remain available in the Alerts page.')}catch(e){setStatus(errorMessage(e))}finally{setBusy(false)}}
 const selected=fences.find(f=>String(f.properties.id)===chosen);const overlay=selected?{type:'FeatureCollection',features:[selected]}:{type:'FeatureCollection',features:fences};
 return <div className="spatial-workspace"><div className="tool-columns"><section className="tool-card"><div className="tool-title"><h2>Monitored zones</h2><p>View predefined and custom zones. Active custom zones are included in anomaly detection.</p></div><label className="field-label">Choose a zone<select value={chosen} onChange={e=>e.target.value?inspect(e.target.value):(version.current++,setChosen(''),setAircraft([]),setBusy(false),setStatus('Choose a zone to inspect recent aircraft.'))}><option value="">All zones</option>{fences.map(f=><option key={f.properties.id} value={f.properties.id}>{f.properties.name}{f.properties.builtin?' / built-in':''}</option>)}</select></label><div className="tool-actions">{chosen&&<button className="secondary" disabled={busy} onClick={()=>inspect(chosen)}>Refresh zone aircraft</button>}{selected&&!selected.properties.builtin&&canManage&&<button className="secondary" disabled={busy} onClick={deactivate}>Deactivate zone</button>}</div><p role="status" className="tool-status">{busy?'Loading...':status||'Choose a zone to see aircraft observed inside it within 30 minutes.'}</p><small className="muted">Built-in zones are configured examples; their names do not establish real restricted airspace.</small></section><section className="tool-card"><div className="tool-title"><h2>Create a polygon zone</h2><p>Enter the boundary points in order. The last point connects to the first.</p></div>{canManage?<form onSubmit={save}><label className="field-label">Zone name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="My monitored area"/></label><label className="field-label">Boundary coordinates<textarea required rows={5} value={coordinates} onChange={e=>setCoordinates(e.target.value)}/></label><small className="muted">One longitude, latitude pair per line; at least three points.</small><button className="primary" disabled={busy}>Save zone</button></form>:<p className="muted">Analyst or admin access is required to create or deactivate zones.</p>}</section></div><ToolMap aircraft={aircraft} overlay={overlay} onTrack={onTrack}/>{chosen&&<Results aircraft={aircraft} onTrack={onTrack}/>}</div>
}
export function LiveFeed({onTrack}:{onTrack:(a:Aircraft)=>void}){const [aircraft,setAircraft]=useState<Aircraft[]>([]),[limit,setLimit]=useState('100'),[busy,setBusy]=useState(false),[status,setStatus]=useState('Request a current snapshot directly from OpenSky. This preview does not save history.');async function load(e:FormEvent){e.preventDefault();setBusy(true);setAircraft([]);try{const {data}=await api.get('/aircraft/live',{params:{limit:Number(limit)}});setAircraft((data.aircraft||[]).map((a:any)=>({type:'Feature',geometry:{type:'Point',coordinates:[a.longitude,a.latitude]},properties:{icao24:a.icao24,callsign:a.callsign,origin_country:a.origin_country,altitude:a.altitude,velocity:a.velocity,heading:a.heading,last_update:a.last_update}})));setStatus(`${data.count} aircraft displayed from ${data.total_tracked} returned by OpenSky. Snapshot: ${new Date(data.timestamp).toLocaleString()}.`)}catch(e){setStatus(errorMessage(e))}finally{setBusy(false)}}return <div className="spatial-workspace"><section className="tool-card"><div className="tool-title"><h2>Live OpenSky snapshot</h2><p>Fetch on demand. Aircraft may not have stored history yet. Requests depend on provider availability and rate limits.</p></div><form onSubmit={load}><div className="tool-fields"><label>Preview limit<select value={limit} onChange={e=>setLimit(e.target.value)}>{[100,1000,5000,10000].map(n=><option key={n}>{n}</option>)}</select></label><button className="primary" disabled={busy}>{busy?'Fetching...':'Fetch live snapshot'}</button></div></form><p className="tool-status" role="status">{status}</p></section><ToolMap aircraft={aircraft} onTrack={onTrack}/><Results aircraft={aircraft} onTrack={onTrack}/></div>}
